services:
    mailhog:
        container_name: mail
        image: 'mailhog/mailhog:latest'
        ports:
            - '2021:8025'

    redis:
        image: 'redis:7.4.1-alpine3.20'
        container_name: redis
        ports:
            - "${DOCKER_REDIS_PORT}:6379"
        networks:
            - app-network
        command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

    mysql:
        container_name: mysql
        image: 'mysql:8.0'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=crm
            - MYSQL_USER=crm-user
            - MYSQL_PASSWORD=password
        ports:
            - '2022:3306'
        networks:
            - app-network

    nginx:
        image: 'nginx:alpine'
        container_name: nginx
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '80:80'
        networks:
            - app-network

    app:
        container_name: php
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        working_dir: /application
        networks:
            - app-network
        depends_on:
            - mysql
            - redis
        volumes:
            - '.:/application'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/cli/conf.d/99-overrides.ini'
        command: php-fpm

    worker:
        build:
            context: .
            dockerfile: ./docker/worker/Dockerfile
        container_name: worker
        working_dir: /application
        volumes:
            - ./:/application
        networks:
            - app-network
        depends_on:
            - mysql
            - redis
        command: supervisord -c /etc/supervisor/conf.d/supervisord.conf


networks:
     app-network:
         driver: bridge
